import requests, json
import pandas as pd
from config import fantasy_base_url

def find_fpl_id(web_name:str):
    r = requests.get(fantasy_base_url + 'bootstrap-static/').json()
    player_data = r['elements']
    return find_player_by_web_name(player_data, web_name)


def find_player_by_web_name(data, name: str):
    df = pd.DataFrame(data)
    df.drop(df.columns.difference(["first_name", "second_name", "id", "web_name"]), axis=1, inplace=True)

    matches_df = df.loc[(df['web_name'] == name)|(df['second_name'] == name)|(df['first_name'] == name)]
    matches_df.drop(["first_name", "second_name"], axis=1, inplace=True)

    if len(matches_df) > 1:
        raise Exception(f"multiple matches found, please specify. \n {matches_df['web_name'].tolist()}")
    elif len(matches_df) == 0:
        raise Exception("no player found")
    
    name_and_id = {
        "web_name": matches_df['web_name'][0],
        "id": matches_df['id'][0].item()
    }
    print(name_and_id)
    return name_and_id

"""
test_data = [
  {
    "chance_of_playing_next_round": 0,
    "chance_of_playing_this_round": 0,
    "code": 438098,
    "cost_change_event": 0,
    "cost_change_event_fall": 0,
    "cost_change_start": -1,
    "cost_change_start_fall": 1,
    "dreamteam_count": 0,
    "element_type": 3,
    "ep_next": "0.0",
    "ep_this": "0.0",
    "event_points": 0,
    "first_name": "Fábio",
    "form": "0.0",
    "id": 1,
    "in_dreamteam": False,
    "news": "Has joined Portuguese side FC Porto on loan for the 2024/25 season",
    "news_added": "2024-08-29T11:06:25.241953Z",
    "now_cost": 54,
    "photo": "438098.jpg",
    "points_per_game": "0.0",
    "second_name": "Ferreira Vieira",
    "selected_by_percent": "0.0",
    "special": False,
    "squad_number": None,
    "status": "u",
    "team": 1,
    "team_code": 3,
    "total_points": 0,
    "transfers_in": 439,
    "transfers_in_event": 0,
    "transfers_out": 2693,
    "transfers_out_event": 7,
    "value_form": "0.0",
    "value_season": "0.0",
    "web_name": "Fábio Vieira",
    "region": None,
    "minutes": 0,
    "goals_scored": 0,
    "assists": 0,
    "clean_sheets": 0,
    "goals_conceded": 0,
    "own_goals": 0,
    "penalties_saved": 0,
    "penalties_missed": 0,
    "yellow_cards": 0,
    "red_cards": 0,
    "saves": 0,
    "bonus": 0,
    "bps": 0,
    "influence": "0.0",
    "creativity": "0.0",
    "threat": "0.0",
    "ict_index": "0.0",
    "starts": 0,
    "expected_goals": "0.00",
    "expected_assists": "0.00",
    "expected_goal_involvements": "0.00",
    "expected_goals_conceded": "0.00",
    "influence_rank": 656,
    "influence_rank_type": 298,
    "creativity_rank": 655,
    "creativity_rank_type": 298,
    "threat_rank": 652,
    "threat_rank_type": 296,
    "ict_index_rank": 656,
    "ict_index_rank_type": 298,
    "corners_and_indirect_freekicks_order": None,
    "corners_and_indirect_freekicks_text": "",
    "direct_freekicks_order": None,
    "direct_freekicks_text": "",
    "penalties_order": None,
    "penalties_text": "",
    "expected_goals_per_90": 0,
    "saves_per_90": 0,
    "expected_assists_per_90": 0,
    "expected_goal_involvements_per_90": 0,
    "expected_goals_conceded_per_90": 0,
    "goals_conceded_per_90": 0,
    "now_cost_rank": 137,
    "now_cost_rank_type": 82,
    "form_rank": 641,
    "form_rank_type": 288,
    "points_per_game_rank": 655,
    "points_per_game_rank_type": 298,
    "selected_rank": 622,
    "selected_rank_type": 276,
    "starts_per_90": 0,
    "clean_sheets_per_90": 0
  },
  {
    "chance_of_playing_next_round": 0,
    "chance_of_playing_this_round": 0,
    "code": 438098,
    "cost_change_event": 0,
    "cost_change_event_fall": 0,
    "cost_change_start": -1,
    "cost_change_start_fall": 1,
    "dreamteam_count": 0,
    "element_type": 3,
    "ep_next": "0.0",
    "ep_this": "0.0",
    "event_points": 0,
    "first_name": "Fábio",
    "form": "0.0",
    "id": 3,
    "in_dreamteam": False,
    "news": "Has joined Portuguese side FC Porto on loan for the 2024/25 season",
    "news_added": "2024-08-29T11:06:25.241953Z",
    "now_cost": 54,
    "photo": "438098.jpg",
    "points_per_game": "0.0",
    "second_name": "Ferreira Vieira number 2",
    "selected_by_percent": "0.0",
    "special": False,
    "squad_number": None,
    "status": "u",
    "team": 1,
    "team_code": 3,
    "total_points": 0,
    "transfers_in": 439,
    "transfers_in_event": 0,
    "transfers_out": 2693,
    "transfers_out_event": 7,
    "value_form": "0.0",
    "value_season": "0.0",
    "web_name": "Fábio Vieira number 2",
    "region": None,
    "minutes": 0,
    "goals_scored": 0,
    "assists": 0,
    "clean_sheets": 0,
    "goals_conceded": 0,
    "own_goals": 0,
    "penalties_saved": 0,
    "penalties_missed": 0,
    "yellow_cards": 0,
    "red_cards": 0,
    "saves": 0,
    "bonus": 0,
    "bps": 0,
    "influence": "0.0",
    "creativity": "0.0",
    "threat": "0.0",
    "ict_index": "0.0",
    "starts": 0,
    "expected_goals": "0.00",
    "expected_assists": "0.00",
    "expected_goal_involvements": "0.00",
    "expected_goals_conceded": "0.00",
    "influence_rank": 656,
    "influence_rank_type": 298,
    "creativity_rank": 655,
    "creativity_rank_type": 298,
    "threat_rank": 652,
    "threat_rank_type": 296,
    "ict_index_rank": 656,
    "ict_index_rank_type": 298,
    "corners_and_indirect_freekicks_order": None,
    "corners_and_indirect_freekicks_text": "",
    "direct_freekicks_order": None,
    "direct_freekicks_text": "",
    "penalties_order": None,
    "penalties_text": "",
    "expected_goals_per_90": 0,
    "saves_per_90": 0,
    "expected_assists_per_90": 0,
    "expected_goal_involvements_per_90": 0,
    "expected_goals_conceded_per_90": 0,
    "goals_conceded_per_90": 0,
    "now_cost_rank": 137,
    "now_cost_rank_type": 82,
    "form_rank": 641,
    "form_rank_type": 288,
    "points_per_game_rank": 655,
    "points_per_game_rank_type": 298,
    "selected_rank": 622,
    "selected_rank_type": 276,
    "starts_per_90": 0,
    "clean_sheets_per_90": 0
  },
  {
  "chance_of_playing_next_round": 100,
  "chance_of_playing_this_round": 100,
  "code": 205651,
  "cost_change_event": 0,
  "cost_change_event_fall": 0,
  "cost_change_start": -2,
  "cost_change_start_fall": 2,
  "dreamteam_count": 0,
  "element_type": 4,
  "ep_next": "1.7",
  "ep_this": "0.7",
  "event_points": 0,
  "first_name": "Gabriel",
  "form": "0.7",
  "id": 2,
  "in_dreamteam": False,
  "news": "",
  "news_added": "2024-08-25T11:00:05.312580Z",
  "now_cost": 68,
  "photo": "205651.jpg",
  "points_per_game": "0.6",
  "second_name": "Fernando de Jesus",
  "selected_by_percent": "0.9",
  "special": False,
  "squad_number": None,
  "status": "a",
  "team": 1,
  "team_code": 3,
  "total_points": 4,
  "transfers_in": 53765,
  "transfers_in_event": 1579,
  "transfers_out": 211053,
  "transfers_out_event": 4793,
  "value_form": "0.1",
  "value_season": "0.6",
  "web_name": "G.Jesus",
  "region": 30,
  "minutes": 93,
  "goals_scored": 0,
  "assists": 0,
  "clean_sheets": 0,
  "goals_conceded": 2,
  "own_goals": 0,
  "penalties_saved": 0,
  "penalties_missed": 0,
  "yellow_cards": 3,
  "red_cards": 0,
  "saves": 0,
  "bonus": 0,
  "bps": 27,
  "influence": "17.0",
  "creativity": "33.0",
  "threat": "60.0",
  "ict_index": "10.9",
  "starts": 1,
  "expected_goals": "0.67",
  "expected_assists": "0.06",
  "expected_goal_involvements": "0.73",
  "expected_goals_conceded": "1.29",
  "influence_rank": 351,
  "influence_rank_type": 33,
  "creativity_rank": 243,
  "creativity_rank_type": 26,
  "threat_rank": 146,
  "threat_rank_type": 28,
  "ict_index_rank": 284,
  "ict_index_rank_type": 32,
  "corners_and_indirect_freekicks_order": None,
  "corners_and_indirect_freekicks_text": "",
  "direct_freekicks_order": None,
  "direct_freekicks_text": "",
  "penalties_order": None,
  "penalties_text": "",
  "expected_goals_per_90": 0.65,
  "saves_per_90": 0,
  "expected_assists_per_90": 0.06,
  "expected_goal_involvements_per_90": 0.71,
  "expected_goals_conceded_per_90": 1.25,
  "goals_conceded_per_90": 1.94,
  "now_cost_rank": 32,
  "now_cost_rank_type": 14,
  "form_rank": 312,
  "form_rank_type": 36,
  "points_per_game_rank": 430,
  "points_per_game_rank_type": 45,
  "selected_rank": 209,
  "selected_rank_type": 36,
  "starts_per_90": 0.97,
  "clean_sheets_per_90": 0
}
]
"""

#tests
#find_player_by_name(test_data, "Fábio")
#find_player_by_name(test_data, "Fábio Vieira")

#find_fpl_id("Gabriel")